---
galaxy_info:
  author: Berik Ashimov
  description: Tinc VPN mesh network setup for Proxmox VE clusters
  license: BSD
  min_ansible_version: "2.10"
  platforms:
    - name: Debian
      versions:
        - bullseye
        - bookworm
    - name: EL
      versions:
        - "8"
        - "9"
  galaxy_tags:
    - proxmox
    - tinc
    - vpn
    - mesh
    - networking

dependencies: []
